spring.datasource.url=jdbc:postgresql://dpg-d89u9899rddc739k2e4g-a.ohio-postgres.render.com:5432/hmpsjf

spring.datasource.username=adarsh

spring.datasource.password=qEiAsZxGKqUrgPe2WGN2MH4WV38DvZlr

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect